#!/usr/bin/env python3
"""
Dump reference outputs from the Python mission worker.

Imports the model directly rather than going through FastAPI, so the
reference can be regenerated with nothing but the standard library — no
server, no dependencies, no network.

    python3 tools/dump_reference.py [out.json]

The result feeds `tools/parity-check.mjs`, which asserts the browser engine
reproduces every one of these numbers.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "worker"))

from app import geo, mission, power, science          # noqa: E402
from app.config import AOI                            # noqa: E402
from app.desalination import schedule                 # noqa: E402

SLIDERS = [0, 0.05, 0.17, 0.32, 0.333, 0.34, 0.5, 0.61, 0.666, 0.67,
           0.72, 0.8, 0.8333, 0.88, 0.94, 0.999]

# The desalination schedule depends on the real Gulf-time hour, so it is
# dumped at a pinned hour and the JS side is asked for the same one.
PINNED_HOUR = 9


def field(slider, nx, ny):
    t = mission.slider_to_loop_t(slider)
    w, s, e, n = AOI["bbox"]
    values, peak = [], 0.0
    for j in range(ny):
        lat = s + (n - s) * (j / (ny - 1))
        for i in range(nx):
            lon = w + (e - w) * (i / (nx - 1))
            v = science.chlorophyll_mg_m3(lat, lon, t)
            peak = max(peak, v)
            values.append(round(v, 3))
    return {"bbox": AOI["bbox"], "nx": nx, "ny": ny, "max": round(peak, 3),
            "values": values}


def main():
    out_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "tools", "reference.json")

    t_active = mission.slider_to_loop_t(0.8333)
    p_active = geo.subsatellite_point(t_active)

    ref = {
        "_note": "Generated by tools/dump_reference.py from the Python worker. "
                 "Regenerate after any change to worker/app/.",
        "sliders": SLIDERS,
        "pinned_hour": PINNED_HOUR,
        "derived": {
            "orbital_velocity_kms": round(geo.orbital_velocity_kms(), 4),
            "ground_speed_kms": round(geo.ground_speed_kms(), 4),
            "array_peak_w": round(power.PEAK_ARRAY_W, 2),
            "soc_envelope": power.soc_bounds(),
        },
        "field": field(0.8333, 24, 12),
        "states": {
            str(s): mission.snapshot(s, include_schedule=False)
            for s in SLIDERS
        },
        "spectrum": science.spectrum(p_active["lat"], p_active["lon"],
                                     phase=t_active, bands=96),
        "desalination": schedule(
            "ACTIVE", t_active,
            __import__("datetime").datetime(2026, 9, 18, PINNED_HOUR, 0,
                                            tzinfo=__import__("datetime").timezone(
                                                __import__("datetime").timedelta(hours=4))),
        ),
    }

    with open(out_path, "w") as fh:
        json.dump(ref, fh, indent=1, sort_keys=True)

    size = os.path.getsize(out_path) / 1024
    print(f"wrote {out_path} ({size:.0f} KB)")
    print(f"  {len(SLIDERS)} full states, "
          f"{len(ref['spectrum']['bands'])} spectral bands, "
          f"{len(ref['field']['values'])} field cells, "
          f"{len(ref['desalination']['plants'])} plants")


if __name__ == "__main__":
    main()
